// <auto-generated />
using System;
using Gladiator.Infrastructure.Data.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Gladiator.Infrastructure.Data.Migrations
{
    [DbContext(typeof(GladiatorContext))]
    [Migration("20220419144419_Initital")]
    partial class Initital
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("ArenaPlayer", b =>
                {
                    b.Property<int>("ArenasId")
                        .HasColumnType("int");

                    b.Property<int>("OwnersId")
                        .HasColumnType("int");

                    b.HasKey("ArenasId", "OwnersId");

                    b.HasIndex("OwnersId");

                    b.ToTable("ArenaPlayer");
                });

            modelBuilder.Entity("Gladiator.Core.Entities.Arena", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Arena");
                });

            modelBuilder.Entity("Gladiator.Core.Entities.Gear", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("Armor")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("Damage")
                        .HasColumnType("int");

                    b.Property<int>("Durability")
                        .HasColumnType("int");

                    b.Property<int>("GladiatorId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Slots")
                        .HasColumnType("int");

                    b.Property<int?>("StatModifiersPercentId")
                        .HasColumnType("int");

                    b.Property<int?>("StatModifiersPointsId")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("Weight")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("GladiatorId");

                    b.HasIndex("StatModifiersPercentId");

                    b.HasIndex("StatModifiersPointsId");

                    b.ToTable("Gear");
                });

            modelBuilder.Entity("Gladiator.Core.Entities.Gladiator", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("ArenaId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("Experience")
                        .HasColumnType("int");

                    b.Property<int>("Health")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PlayerId")
                        .HasColumnType("int");

                    b.Property<int>("SchoolId")
                        .HasColumnType("int");

                    b.Property<int>("StatUpdatesCountId")
                        .HasColumnType("int");

                    b.Property<int>("StatsId")
                        .HasColumnType("int");

                    b.Property<int>("TotalExperience")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ArenaId");

                    b.HasIndex("PlayerId");

                    b.HasIndex("SchoolId");

                    b.HasIndex("StatUpdatesCountId");

                    b.HasIndex("StatsId");

                    b.ToTable("Gladiator");
                });

            modelBuilder.Entity("Gladiator.Core.Entities.Player", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Player");
                });

            modelBuilder.Entity("Gladiator.Core.Entities.School", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("ArenaId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PlayerId")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ArenaId");

                    b.HasIndex("PlayerId");

                    b.ToTable("School");
                });

            modelBuilder.Entity("Gladiator.Core.Entities.Stats", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("Agility")
                        .HasColumnType("int");

                    b.Property<int>("Constitution")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("Dexterity")
                        .HasColumnType("int");

                    b.Property<int>("Intelligence")
                        .HasColumnType("int");

                    b.Property<int>("Strength")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Stats");
                });

            modelBuilder.Entity("ArenaPlayer", b =>
                {
                    b.HasOne("Gladiator.Core.Entities.Arena", null)
                        .WithMany()
                        .HasForeignKey("ArenasId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Gladiator.Core.Entities.Player", null)
                        .WithMany()
                        .HasForeignKey("OwnersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Gladiator.Core.Entities.Gear", b =>
                {
                    b.HasOne("Gladiator.Core.Entities.Gladiator", "Gladiator")
                        .WithMany("Gear")
                        .HasForeignKey("GladiatorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Gladiator.Core.Entities.Stats", "StatModifiersPercent")
                        .WithMany()
                        .HasForeignKey("StatModifiersPercentId");

                    b.HasOne("Gladiator.Core.Entities.Stats", "StatModifiersPoints")
                        .WithMany()
                        .HasForeignKey("StatModifiersPointsId");

                    b.Navigation("Gladiator");

                    b.Navigation("StatModifiersPercent");

                    b.Navigation("StatModifiersPoints");
                });

            modelBuilder.Entity("Gladiator.Core.Entities.Gladiator", b =>
                {
                    b.HasOne("Gladiator.Core.Entities.Arena", "Arena")
                        .WithMany("Gladiators")
                        .HasForeignKey("ArenaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Gladiator.Core.Entities.Player", "Player")
                        .WithMany("Gladiators")
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Gladiator.Core.Entities.School", "School")
                        .WithMany("Gladiators")
                        .HasForeignKey("SchoolId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Gladiator.Core.Entities.Stats", "StatUpdatesCount")
                        .WithMany()
                        .HasForeignKey("StatUpdatesCountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Gladiator.Core.Entities.Stats", "Stats")
                        .WithMany()
                        .HasForeignKey("StatsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Arena");

                    b.Navigation("Player");

                    b.Navigation("School");

                    b.Navigation("StatUpdatesCount");

                    b.Navigation("Stats");
                });

            modelBuilder.Entity("Gladiator.Core.Entities.School", b =>
                {
                    b.HasOne("Gladiator.Core.Entities.Arena", "Arena")
                        .WithMany("Schools")
                        .HasForeignKey("ArenaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Gladiator.Core.Entities.Player", "Player")
                        .WithMany("Schools")
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Arena");

                    b.Navigation("Player");
                });

            modelBuilder.Entity("Gladiator.Core.Entities.Arena", b =>
                {
                    b.Navigation("Gladiators");

                    b.Navigation("Schools");
                });

            modelBuilder.Entity("Gladiator.Core.Entities.Gladiator", b =>
                {
                    b.Navigation("Gear");
                });

            modelBuilder.Entity("Gladiator.Core.Entities.Player", b =>
                {
                    b.Navigation("Gladiators");

                    b.Navigation("Schools");
                });

            modelBuilder.Entity("Gladiator.Core.Entities.School", b =>
                {
                    b.Navigation("Gladiators");
                });
#pragma warning restore 612, 618
        }
    }
}
