// <auto-generated />
using System;
using Gladiator.Infrastructure.Data.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Gladiator.Infrastructure.Data.Migrations
{
    [DbContext(typeof(GladiatorContext))]
    partial class GladiatorContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("ArenaPlayer", b =>
                {
                    b.Property<int>("OwnedArenasId")
                        .HasColumnType("int");

                    b.Property<int>("OwnersId")
                        .HasColumnType("int");

                    b.HasKey("OwnedArenasId", "OwnersId");

                    b.HasIndex("OwnersId");

                    b.ToTable("ArenaPlayer");
                });

            modelBuilder.Entity("Gladiator.Core.Entities.Arena", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Arena");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2022, 4, 20, 14, 4, 7, 562, DateTimeKind.Utc).AddTicks(7361),
                            Name = "Arena 1",
                            UpdatedAt = new DateTime(2022, 4, 20, 14, 4, 7, 562, DateTimeKind.Utc).AddTicks(7362)
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2022, 4, 20, 14, 4, 7, 562, DateTimeKind.Utc).AddTicks(7364),
                            Name = "Arena 2",
                            UpdatedAt = new DateTime(2022, 4, 20, 14, 4, 7, 562, DateTimeKind.Utc).AddTicks(7364)
                        });
                });

            modelBuilder.Entity("Gladiator.Core.Entities.BattleLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("GladiatorId")
                        .HasColumnType("int");

                    b.Property<string>("Log")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("GladiatorId");

                    b.ToTable("BattleLog");
                });

            modelBuilder.Entity("Gladiator.Core.Entities.Gear", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("Armor")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("Damage")
                        .HasColumnType("int");

                    b.Property<int>("Durability")
                        .HasColumnType("int");

                    b.Property<int>("GladiatorId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Slots")
                        .HasColumnType("int");

                    b.Property<int>("StatModifiersPercentId")
                        .HasColumnType("int");

                    b.Property<int>("StatModifiersPointsId")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("Weight")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("GladiatorId");

                    b.HasIndex("StatModifiersPercentId")
                        .IsUnique();

                    b.HasIndex("StatModifiersPointsId")
                        .IsUnique();

                    b.ToTable("Gear");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Armor = 1,
                            CreatedAt = new DateTime(2022, 4, 20, 14, 4, 7, 562, DateTimeKind.Utc).AddTicks(7417),
                            Damage = 1,
                            Durability = 1,
                            GladiatorId = 1,
                            Name = "Gear 1",
                            Slots = 1,
                            StatModifiersPercentId = 25,
                            StatModifiersPointsId = 26,
                            UpdatedAt = new DateTime(2022, 4, 20, 14, 4, 7, 562, DateTimeKind.Utc).AddTicks(7417),
                            Weight = 1
                        },
                        new
                        {
                            Id = 2,
                            Armor = 2,
                            CreatedAt = new DateTime(2022, 4, 20, 14, 4, 7, 562, DateTimeKind.Utc).AddTicks(7419),
                            Damage = 2,
                            Durability = 2,
                            GladiatorId = 2,
                            Name = "Gear 2",
                            Slots = 2,
                            StatModifiersPercentId = 27,
                            StatModifiersPointsId = 28,
                            UpdatedAt = new DateTime(2022, 4, 20, 14, 4, 7, 562, DateTimeKind.Utc).AddTicks(7419),
                            Weight = 2
                        },
                        new
                        {
                            Id = 3,
                            Armor = 3,
                            CreatedAt = new DateTime(2022, 4, 20, 14, 4, 7, 562, DateTimeKind.Utc).AddTicks(7420),
                            Damage = 3,
                            Durability = 3,
                            GladiatorId = 3,
                            Name = "Gear 3",
                            Slots = 3,
                            StatModifiersPercentId = 29,
                            StatModifiersPointsId = 30,
                            UpdatedAt = new DateTime(2022, 4, 20, 14, 4, 7, 562, DateTimeKind.Utc).AddTicks(7421),
                            Weight = 3
                        },
                        new
                        {
                            Id = 4,
                            Armor = 4,
                            CreatedAt = new DateTime(2022, 4, 20, 14, 4, 7, 562, DateTimeKind.Utc).AddTicks(7422),
                            Damage = 4,
                            Durability = 4,
                            GladiatorId = 4,
                            Name = "Gear 4",
                            Slots = 4,
                            StatModifiersPercentId = 31,
                            StatModifiersPointsId = 32,
                            UpdatedAt = new DateTime(2022, 4, 20, 14, 4, 7, 562, DateTimeKind.Utc).AddTicks(7423),
                            Weight = 4
                        },
                        new
                        {
                            Id = 5,
                            Armor = 5,
                            CreatedAt = new DateTime(2022, 4, 20, 14, 4, 7, 562, DateTimeKind.Utc).AddTicks(7424),
                            Damage = 5,
                            Durability = 5,
                            GladiatorId = 5,
                            Name = "Gear 5",
                            Slots = 5,
                            StatModifiersPercentId = 33,
                            StatModifiersPointsId = 34,
                            UpdatedAt = new DateTime(2022, 4, 20, 14, 4, 7, 562, DateTimeKind.Utc).AddTicks(7425),
                            Weight = 5
                        },
                        new
                        {
                            Id = 6,
                            Armor = 6,
                            CreatedAt = new DateTime(2022, 4, 20, 14, 4, 7, 562, DateTimeKind.Utc).AddTicks(7426),
                            Damage = 6,
                            Durability = 6,
                            GladiatorId = 6,
                            Name = "Gear 6",
                            Slots = 6,
                            StatModifiersPercentId = 35,
                            StatModifiersPointsId = 36,
                            UpdatedAt = new DateTime(2022, 4, 20, 14, 4, 7, 562, DateTimeKind.Utc).AddTicks(7427),
                            Weight = 6
                        },
                        new
                        {
                            Id = 7,
                            Armor = 7,
                            CreatedAt = new DateTime(2022, 4, 20, 14, 4, 7, 562, DateTimeKind.Utc).AddTicks(7429),
                            Damage = 7,
                            Durability = 7,
                            GladiatorId = 7,
                            Name = "Gear 7",
                            Slots = 7,
                            StatModifiersPercentId = 37,
                            StatModifiersPointsId = 38,
                            UpdatedAt = new DateTime(2022, 4, 20, 14, 4, 7, 562, DateTimeKind.Utc).AddTicks(7429),
                            Weight = 7
                        },
                        new
                        {
                            Id = 8,
                            Armor = 8,
                            CreatedAt = new DateTime(2022, 4, 20, 14, 4, 7, 562, DateTimeKind.Utc).AddTicks(7430),
                            Damage = 8,
                            Durability = 8,
                            GladiatorId = 8,
                            Name = "Gear 8",
                            Slots = 8,
                            StatModifiersPercentId = 39,
                            StatModifiersPointsId = 40,
                            UpdatedAt = new DateTime(2022, 4, 20, 14, 4, 7, 562, DateTimeKind.Utc).AddTicks(7431),
                            Weight = 8
                        },
                        new
                        {
                            Id = 9,
                            Armor = 9,
                            CreatedAt = new DateTime(2022, 4, 20, 14, 4, 7, 562, DateTimeKind.Utc).AddTicks(7432),
                            Damage = 9,
                            Durability = 9,
                            GladiatorId = 9,
                            Name = "Gear 9",
                            Slots = 9,
                            StatModifiersPercentId = 41,
                            StatModifiersPointsId = 42,
                            UpdatedAt = new DateTime(2022, 4, 20, 14, 4, 7, 562, DateTimeKind.Utc).AddTicks(7433),
                            Weight = 9
                        },
                        new
                        {
                            Id = 10,
                            Armor = 10,
                            CreatedAt = new DateTime(2022, 4, 20, 14, 4, 7, 562, DateTimeKind.Utc).AddTicks(7434),
                            Damage = 10,
                            Durability = 10,
                            GladiatorId = 10,
                            Name = "Gear 10",
                            Slots = 10,
                            StatModifiersPercentId = 43,
                            StatModifiersPointsId = 44,
                            UpdatedAt = new DateTime(2022, 4, 20, 14, 4, 7, 562, DateTimeKind.Utc).AddTicks(7434),
                            Weight = 10
                        },
                        new
                        {
                            Id = 11,
                            Armor = 11,
                            CreatedAt = new DateTime(2022, 4, 20, 14, 4, 7, 562, DateTimeKind.Utc).AddTicks(7436),
                            Damage = 11,
                            Durability = 11,
                            GladiatorId = 11,
                            Name = "Gear 11",
                            Slots = 11,
                            StatModifiersPercentId = 45,
                            StatModifiersPointsId = 46,
                            UpdatedAt = new DateTime(2022, 4, 20, 14, 4, 7, 562, DateTimeKind.Utc).AddTicks(7436),
                            Weight = 11
                        },
                        new
                        {
                            Id = 12,
                            Armor = 12,
                            CreatedAt = new DateTime(2022, 4, 20, 14, 4, 7, 562, DateTimeKind.Utc).AddTicks(7437),
                            Damage = 12,
                            Durability = 12,
                            GladiatorId = 12,
                            Name = "Gear 12",
                            Slots = 12,
                            StatModifiersPercentId = 47,
                            StatModifiersPointsId = 48,
                            UpdatedAt = new DateTime(2022, 4, 20, 14, 4, 7, 562, DateTimeKind.Utc).AddTicks(7438),
                            Weight = 12
                        });
                });

            modelBuilder.Entity("Gladiator.Core.Entities.Gladiator", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("Experience")
                        .HasColumnType("int");

                    b.Property<int>("Health")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PlayerId")
                        .HasColumnType("int");

                    b.Property<int>("SchoolId")
                        .HasColumnType("int");

                    b.Property<int>("StatUpdatesId")
                        .HasColumnType("int");

                    b.Property<int>("StatsId")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("PlayerId");

                    b.HasIndex("SchoolId");

                    b.HasIndex("StatUpdatesId")
                        .IsUnique();

                    b.HasIndex("StatsId")
                        .IsUnique();

                    b.ToTable("Gladiator");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2022, 4, 20, 14, 4, 7, 562, DateTimeKind.Utc).AddTicks(7300),
                            Experience = 1,
                            Health = 1,
                            Name = "Gladiator 1",
                            PlayerId = 1,
                            SchoolId = 1,
                            StatUpdatesId = 2,
                            StatsId = 1,
                            UpdatedAt = new DateTime(2022, 4, 20, 14, 4, 7, 562, DateTimeKind.Utc).AddTicks(7301)
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2022, 4, 20, 14, 4, 7, 562, DateTimeKind.Utc).AddTicks(7303),
                            Experience = 2,
                            Health = 2,
                            Name = "Gladiator 2",
                            PlayerId = 1,
                            SchoolId = 1,
                            StatUpdatesId = 4,
                            StatsId = 3,
                            UpdatedAt = new DateTime(2022, 4, 20, 14, 4, 7, 562, DateTimeKind.Utc).AddTicks(7304)
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2022, 4, 20, 14, 4, 7, 562, DateTimeKind.Utc).AddTicks(7305),
                            Experience = 3,
                            Health = 3,
                            Name = "Gladiator 3",
                            PlayerId = 1,
                            SchoolId = 1,
                            StatUpdatesId = 6,
                            StatsId = 5,
                            UpdatedAt = new DateTime(2022, 4, 20, 14, 4, 7, 562, DateTimeKind.Utc).AddTicks(7305)
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2022, 4, 20, 14, 4, 7, 562, DateTimeKind.Utc).AddTicks(7307),
                            Experience = 4,
                            Health = 4,
                            Name = "Gladiator 4",
                            PlayerId = 2,
                            SchoolId = 2,
                            StatUpdatesId = 8,
                            StatsId = 7,
                            UpdatedAt = new DateTime(2022, 4, 20, 14, 4, 7, 562, DateTimeKind.Utc).AddTicks(7307)
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2022, 4, 20, 14, 4, 7, 562, DateTimeKind.Utc).AddTicks(7309),
                            Experience = 5,
                            Health = 5,
                            Name = "Gladiator 5",
                            PlayerId = 2,
                            SchoolId = 2,
                            StatUpdatesId = 10,
                            StatsId = 9,
                            UpdatedAt = new DateTime(2022, 4, 20, 14, 4, 7, 562, DateTimeKind.Utc).AddTicks(7309)
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTime(2022, 4, 20, 14, 4, 7, 562, DateTimeKind.Utc).AddTicks(7310),
                            Experience = 6,
                            Health = 6,
                            Name = "Gladiator 6",
                            PlayerId = 2,
                            SchoolId = 2,
                            StatUpdatesId = 12,
                            StatsId = 11,
                            UpdatedAt = new DateTime(2022, 4, 20, 14, 4, 7, 562, DateTimeKind.Utc).AddTicks(7311)
                        },
                        new
                        {
                            Id = 7,
                            CreatedAt = new DateTime(2022, 4, 20, 14, 4, 7, 562, DateTimeKind.Utc).AddTicks(7312),
                            Experience = 7,
                            Health = 7,
                            Name = "Gladiator 7",
                            PlayerId = 3,
                            SchoolId = 3,
                            StatUpdatesId = 14,
                            StatsId = 13,
                            UpdatedAt = new DateTime(2022, 4, 20, 14, 4, 7, 562, DateTimeKind.Utc).AddTicks(7312)
                        },
                        new
                        {
                            Id = 8,
                            CreatedAt = new DateTime(2022, 4, 20, 14, 4, 7, 562, DateTimeKind.Utc).AddTicks(7314),
                            Experience = 8,
                            Health = 8,
                            Name = "Gladiator 8",
                            PlayerId = 3,
                            SchoolId = 3,
                            StatUpdatesId = 16,
                            StatsId = 15,
                            UpdatedAt = new DateTime(2022, 4, 20, 14, 4, 7, 562, DateTimeKind.Utc).AddTicks(7314)
                        },
                        new
                        {
                            Id = 9,
                            CreatedAt = new DateTime(2022, 4, 20, 14, 4, 7, 562, DateTimeKind.Utc).AddTicks(7315),
                            Experience = 9,
                            Health = 9,
                            Name = "Gladiator 9",
                            PlayerId = 3,
                            SchoolId = 3,
                            StatUpdatesId = 18,
                            StatsId = 17,
                            UpdatedAt = new DateTime(2022, 4, 20, 14, 4, 7, 562, DateTimeKind.Utc).AddTicks(7316)
                        },
                        new
                        {
                            Id = 10,
                            CreatedAt = new DateTime(2022, 4, 20, 14, 4, 7, 562, DateTimeKind.Utc).AddTicks(7317),
                            Experience = 10,
                            Health = 10,
                            Name = "Gladiator 10",
                            PlayerId = 4,
                            SchoolId = 4,
                            StatUpdatesId = 20,
                            StatsId = 19,
                            UpdatedAt = new DateTime(2022, 4, 20, 14, 4, 7, 562, DateTimeKind.Utc).AddTicks(7317)
                        },
                        new
                        {
                            Id = 11,
                            CreatedAt = new DateTime(2022, 4, 20, 14, 4, 7, 562, DateTimeKind.Utc).AddTicks(7319),
                            Experience = 11,
                            Health = 11,
                            Name = "Gladiator 11",
                            PlayerId = 4,
                            SchoolId = 4,
                            StatUpdatesId = 22,
                            StatsId = 21,
                            UpdatedAt = new DateTime(2022, 4, 20, 14, 4, 7, 562, DateTimeKind.Utc).AddTicks(7319)
                        },
                        new
                        {
                            Id = 12,
                            CreatedAt = new DateTime(2022, 4, 20, 14, 4, 7, 562, DateTimeKind.Utc).AddTicks(7321),
                            Experience = 12,
                            Health = 12,
                            Name = "Gladiator 12",
                            PlayerId = 4,
                            SchoolId = 4,
                            StatUpdatesId = 24,
                            StatsId = 23,
                            UpdatedAt = new DateTime(2022, 4, 20, 14, 4, 7, 562, DateTimeKind.Utc).AddTicks(7322)
                        });
                });

            modelBuilder.Entity("Gladiator.Core.Entities.Player", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Player");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2022, 4, 20, 14, 4, 7, 562, DateTimeKind.Utc).AddTicks(7051),
                            Name = "Player 1",
                            UpdatedAt = new DateTime(2022, 4, 20, 14, 4, 7, 562, DateTimeKind.Utc).AddTicks(7055)
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2022, 4, 20, 14, 4, 7, 562, DateTimeKind.Utc).AddTicks(7057),
                            Name = "Player 2",
                            UpdatedAt = new DateTime(2022, 4, 20, 14, 4, 7, 562, DateTimeKind.Utc).AddTicks(7057)
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2022, 4, 20, 14, 4, 7, 562, DateTimeKind.Utc).AddTicks(7058),
                            Name = "Player 3",
                            UpdatedAt = new DateTime(2022, 4, 20, 14, 4, 7, 562, DateTimeKind.Utc).AddTicks(7058)
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2022, 4, 20, 14, 4, 7, 562, DateTimeKind.Utc).AddTicks(7059),
                            Name = "Player 4",
                            UpdatedAt = new DateTime(2022, 4, 20, 14, 4, 7, 562, DateTimeKind.Utc).AddTicks(7060)
                        });
                });

            modelBuilder.Entity("Gladiator.Core.Entities.School", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("ArenaId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PlayerId")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ArenaId");

                    b.HasIndex("PlayerId");

                    b.ToTable("School");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ArenaId = 1,
                            CreatedAt = new DateTime(2022, 4, 20, 14, 4, 7, 562, DateTimeKind.Utc).AddTicks(7387),
                            Name = "School 1",
                            PlayerId = 1,
                            UpdatedAt = new DateTime(2022, 4, 20, 14, 4, 7, 562, DateTimeKind.Utc).AddTicks(7387)
                        },
                        new
                        {
                            Id = 2,
                            ArenaId = 1,
                            CreatedAt = new DateTime(2022, 4, 20, 14, 4, 7, 562, DateTimeKind.Utc).AddTicks(7388),
                            Name = "School 2",
                            PlayerId = 2,
                            UpdatedAt = new DateTime(2022, 4, 20, 14, 4, 7, 562, DateTimeKind.Utc).AddTicks(7389)
                        },
                        new
                        {
                            Id = 3,
                            ArenaId = 2,
                            CreatedAt = new DateTime(2022, 4, 20, 14, 4, 7, 562, DateTimeKind.Utc).AddTicks(7390),
                            Name = "School 3",
                            PlayerId = 3,
                            UpdatedAt = new DateTime(2022, 4, 20, 14, 4, 7, 562, DateTimeKind.Utc).AddTicks(7390)
                        },
                        new
                        {
                            Id = 4,
                            ArenaId = 2,
                            CreatedAt = new DateTime(2022, 4, 20, 14, 4, 7, 562, DateTimeKind.Utc).AddTicks(7391),
                            Name = "School 4",
                            PlayerId = 4,
                            UpdatedAt = new DateTime(2022, 4, 20, 14, 4, 7, 562, DateTimeKind.Utc).AddTicks(7392)
                        });
                });

            modelBuilder.Entity("Gladiator.Core.Entities.Stats", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("Agility")
                        .HasColumnType("int");

                    b.Property<int>("Constitution")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("Dexterity")
                        .HasColumnType("int");

                    b.Property<int>("Intelligence")
                        .HasColumnType("int");

                    b.Property<int>("Strength")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Stats");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Agility = 1,
                            Constitution = 1,
                            CreatedAt = new DateTime(2022, 4, 20, 14, 4, 7, 562, DateTimeKind.Utc).AddTicks(7468),
                            Dexterity = 1,
                            Intelligence = 1,
                            Strength = 1,
                            UpdatedAt = new DateTime(2022, 4, 20, 14, 4, 7, 562, DateTimeKind.Utc).AddTicks(7469)
                        },
                        new
                        {
                            Id = 2,
                            Agility = 2,
                            Constitution = 2,
                            CreatedAt = new DateTime(2022, 4, 20, 14, 4, 7, 562, DateTimeKind.Utc).AddTicks(7473),
                            Dexterity = 2,
                            Intelligence = 2,
                            Strength = 2,
                            UpdatedAt = new DateTime(2022, 4, 20, 14, 4, 7, 562, DateTimeKind.Utc).AddTicks(7474)
                        },
                        new
                        {
                            Id = 3,
                            Agility = 3,
                            Constitution = 3,
                            CreatedAt = new DateTime(2022, 4, 20, 14, 4, 7, 562, DateTimeKind.Utc).AddTicks(7474),
                            Dexterity = 3,
                            Intelligence = 3,
                            Strength = 3,
                            UpdatedAt = new DateTime(2022, 4, 20, 14, 4, 7, 562, DateTimeKind.Utc).AddTicks(7475)
                        },
                        new
                        {
                            Id = 4,
                            Agility = 4,
                            Constitution = 4,
                            CreatedAt = new DateTime(2022, 4, 20, 14, 4, 7, 562, DateTimeKind.Utc).AddTicks(7475),
                            Dexterity = 4,
                            Intelligence = 4,
                            Strength = 4,
                            UpdatedAt = new DateTime(2022, 4, 20, 14, 4, 7, 562, DateTimeKind.Utc).AddTicks(7476)
                        },
                        new
                        {
                            Id = 5,
                            Agility = 5,
                            Constitution = 5,
                            CreatedAt = new DateTime(2022, 4, 20, 14, 4, 7, 562, DateTimeKind.Utc).AddTicks(7476),
                            Dexterity = 5,
                            Intelligence = 5,
                            Strength = 5,
                            UpdatedAt = new DateTime(2022, 4, 20, 14, 4, 7, 562, DateTimeKind.Utc).AddTicks(7476)
                        },
                        new
                        {
                            Id = 6,
                            Agility = 6,
                            Constitution = 6,
                            CreatedAt = new DateTime(2022, 4, 20, 14, 4, 7, 562, DateTimeKind.Utc).AddTicks(7478),
                            Dexterity = 6,
                            Intelligence = 6,
                            Strength = 6,
                            UpdatedAt = new DateTime(2022, 4, 20, 14, 4, 7, 562, DateTimeKind.Utc).AddTicks(7478)
                        },
                        new
                        {
                            Id = 7,
                            Agility = 7,
                            Constitution = 7,
                            CreatedAt = new DateTime(2022, 4, 20, 14, 4, 7, 562, DateTimeKind.Utc).AddTicks(7479),
                            Dexterity = 7,
                            Intelligence = 7,
                            Strength = 7,
                            UpdatedAt = new DateTime(2022, 4, 20, 14, 4, 7, 562, DateTimeKind.Utc).AddTicks(7480)
                        },
                        new
                        {
                            Id = 8,
                            Agility = 8,
                            Constitution = 8,
                            CreatedAt = new DateTime(2022, 4, 20, 14, 4, 7, 562, DateTimeKind.Utc).AddTicks(7480),
                            Dexterity = 8,
                            Intelligence = 8,
                            Strength = 8,
                            UpdatedAt = new DateTime(2022, 4, 20, 14, 4, 7, 562, DateTimeKind.Utc).AddTicks(7480)
                        },
                        new
                        {
                            Id = 9,
                            Agility = 9,
                            Constitution = 9,
                            CreatedAt = new DateTime(2022, 4, 20, 14, 4, 7, 562, DateTimeKind.Utc).AddTicks(7481),
                            Dexterity = 9,
                            Intelligence = 9,
                            Strength = 9,
                            UpdatedAt = new DateTime(2022, 4, 20, 14, 4, 7, 562, DateTimeKind.Utc).AddTicks(7481)
                        },
                        new
                        {
                            Id = 10,
                            Agility = 10,
                            Constitution = 10,
                            CreatedAt = new DateTime(2022, 4, 20, 14, 4, 7, 562, DateTimeKind.Utc).AddTicks(7483),
                            Dexterity = 10,
                            Intelligence = 10,
                            Strength = 10,
                            UpdatedAt = new DateTime(2022, 4, 20, 14, 4, 7, 562, DateTimeKind.Utc).AddTicks(7483)
                        },
                        new
                        {
                            Id = 11,
                            Agility = 11,
                            Constitution = 11,
                            CreatedAt = new DateTime(2022, 4, 20, 14, 4, 7, 562, DateTimeKind.Utc).AddTicks(7484),
                            Dexterity = 11,
                            Intelligence = 11,
                            Strength = 11,
                            UpdatedAt = new DateTime(2022, 4, 20, 14, 4, 7, 562, DateTimeKind.Utc).AddTicks(7484)
                        },
                        new
                        {
                            Id = 12,
                            Agility = 12,
                            Constitution = 12,
                            CreatedAt = new DateTime(2022, 4, 20, 14, 4, 7, 562, DateTimeKind.Utc).AddTicks(7484),
                            Dexterity = 12,
                            Intelligence = 12,
                            Strength = 12,
                            UpdatedAt = new DateTime(2022, 4, 20, 14, 4, 7, 562, DateTimeKind.Utc).AddTicks(7485)
                        },
                        new
                        {
                            Id = 13,
                            Agility = 13,
                            Constitution = 13,
                            CreatedAt = new DateTime(2022, 4, 20, 14, 4, 7, 562, DateTimeKind.Utc).AddTicks(7485),
                            Dexterity = 13,
                            Intelligence = 13,
                            Strength = 13,
                            UpdatedAt = new DateTime(2022, 4, 20, 14, 4, 7, 562, DateTimeKind.Utc).AddTicks(7486)
                        },
                        new
                        {
                            Id = 14,
                            Agility = 14,
                            Constitution = 14,
                            CreatedAt = new DateTime(2022, 4, 20, 14, 4, 7, 562, DateTimeKind.Utc).AddTicks(7533),
                            Dexterity = 14,
                            Intelligence = 14,
                            Strength = 14,
                            UpdatedAt = new DateTime(2022, 4, 20, 14, 4, 7, 562, DateTimeKind.Utc).AddTicks(7534)
                        },
                        new
                        {
                            Id = 15,
                            Agility = 15,
                            Constitution = 15,
                            CreatedAt = new DateTime(2022, 4, 20, 14, 4, 7, 562, DateTimeKind.Utc).AddTicks(7535),
                            Dexterity = 15,
                            Intelligence = 15,
                            Strength = 15,
                            UpdatedAt = new DateTime(2022, 4, 20, 14, 4, 7, 562, DateTimeKind.Utc).AddTicks(7535)
                        },
                        new
                        {
                            Id = 16,
                            Agility = 16,
                            Constitution = 16,
                            CreatedAt = new DateTime(2022, 4, 20, 14, 4, 7, 562, DateTimeKind.Utc).AddTicks(7536),
                            Dexterity = 16,
                            Intelligence = 16,
                            Strength = 16,
                            UpdatedAt = new DateTime(2022, 4, 20, 14, 4, 7, 562, DateTimeKind.Utc).AddTicks(7536)
                        },
                        new
                        {
                            Id = 17,
                            Agility = 17,
                            Constitution = 17,
                            CreatedAt = new DateTime(2022, 4, 20, 14, 4, 7, 562, DateTimeKind.Utc).AddTicks(7536),
                            Dexterity = 17,
                            Intelligence = 17,
                            Strength = 17,
                            UpdatedAt = new DateTime(2022, 4, 20, 14, 4, 7, 562, DateTimeKind.Utc).AddTicks(7537)
                        },
                        new
                        {
                            Id = 18,
                            Agility = 18,
                            Constitution = 18,
                            CreatedAt = new DateTime(2022, 4, 20, 14, 4, 7, 562, DateTimeKind.Utc).AddTicks(7539),
                            Dexterity = 18,
                            Intelligence = 18,
                            Strength = 18,
                            UpdatedAt = new DateTime(2022, 4, 20, 14, 4, 7, 562, DateTimeKind.Utc).AddTicks(7539)
                        },
                        new
                        {
                            Id = 19,
                            Agility = 19,
                            Constitution = 19,
                            CreatedAt = new DateTime(2022, 4, 20, 14, 4, 7, 562, DateTimeKind.Utc).AddTicks(7540),
                            Dexterity = 19,
                            Intelligence = 19,
                            Strength = 19,
                            UpdatedAt = new DateTime(2022, 4, 20, 14, 4, 7, 562, DateTimeKind.Utc).AddTicks(7540)
                        },
                        new
                        {
                            Id = 20,
                            Agility = 20,
                            Constitution = 20,
                            CreatedAt = new DateTime(2022, 4, 20, 14, 4, 7, 562, DateTimeKind.Utc).AddTicks(7541),
                            Dexterity = 20,
                            Intelligence = 20,
                            Strength = 20,
                            UpdatedAt = new DateTime(2022, 4, 20, 14, 4, 7, 562, DateTimeKind.Utc).AddTicks(7541)
                        },
                        new
                        {
                            Id = 21,
                            Agility = 21,
                            Constitution = 21,
                            CreatedAt = new DateTime(2022, 4, 20, 14, 4, 7, 562, DateTimeKind.Utc).AddTicks(7541),
                            Dexterity = 21,
                            Intelligence = 21,
                            Strength = 21,
                            UpdatedAt = new DateTime(2022, 4, 20, 14, 4, 7, 562, DateTimeKind.Utc).AddTicks(7542)
                        },
                        new
                        {
                            Id = 22,
                            Agility = 22,
                            Constitution = 22,
                            CreatedAt = new DateTime(2022, 4, 20, 14, 4, 7, 562, DateTimeKind.Utc).AddTicks(7542),
                            Dexterity = 22,
                            Intelligence = 22,
                            Strength = 22,
                            UpdatedAt = new DateTime(2022, 4, 20, 14, 4, 7, 562, DateTimeKind.Utc).AddTicks(7542)
                        },
                        new
                        {
                            Id = 23,
                            Agility = 23,
                            Constitution = 23,
                            CreatedAt = new DateTime(2022, 4, 20, 14, 4, 7, 562, DateTimeKind.Utc).AddTicks(7543),
                            Dexterity = 23,
                            Intelligence = 23,
                            Strength = 23,
                            UpdatedAt = new DateTime(2022, 4, 20, 14, 4, 7, 562, DateTimeKind.Utc).AddTicks(7543)
                        },
                        new
                        {
                            Id = 24,
                            Agility = 24,
                            Constitution = 24,
                            CreatedAt = new DateTime(2022, 4, 20, 14, 4, 7, 562, DateTimeKind.Utc).AddTicks(7544),
                            Dexterity = 24,
                            Intelligence = 24,
                            Strength = 24,
                            UpdatedAt = new DateTime(2022, 4, 20, 14, 4, 7, 562, DateTimeKind.Utc).AddTicks(7544)
                        },
                        new
                        {
                            Id = 25,
                            Agility = 25,
                            Constitution = 25,
                            CreatedAt = new DateTime(2022, 4, 20, 14, 4, 7, 562, DateTimeKind.Utc).AddTicks(7545),
                            Dexterity = 25,
                            Intelligence = 25,
                            Strength = 25,
                            UpdatedAt = new DateTime(2022, 4, 20, 14, 4, 7, 562, DateTimeKind.Utc).AddTicks(7545)
                        },
                        new
                        {
                            Id = 26,
                            Agility = 26,
                            Constitution = 26,
                            CreatedAt = new DateTime(2022, 4, 20, 14, 4, 7, 562, DateTimeKind.Utc).AddTicks(7545),
                            Dexterity = 26,
                            Intelligence = 26,
                            Strength = 26,
                            UpdatedAt = new DateTime(2022, 4, 20, 14, 4, 7, 562, DateTimeKind.Utc).AddTicks(7546)
                        },
                        new
                        {
                            Id = 27,
                            Agility = 27,
                            Constitution = 27,
                            CreatedAt = new DateTime(2022, 4, 20, 14, 4, 7, 562, DateTimeKind.Utc).AddTicks(7546),
                            Dexterity = 27,
                            Intelligence = 27,
                            Strength = 27,
                            UpdatedAt = new DateTime(2022, 4, 20, 14, 4, 7, 562, DateTimeKind.Utc).AddTicks(7546)
                        },
                        new
                        {
                            Id = 28,
                            Agility = 28,
                            Constitution = 28,
                            CreatedAt = new DateTime(2022, 4, 20, 14, 4, 7, 562, DateTimeKind.Utc).AddTicks(7547),
                            Dexterity = 28,
                            Intelligence = 28,
                            Strength = 28,
                            UpdatedAt = new DateTime(2022, 4, 20, 14, 4, 7, 562, DateTimeKind.Utc).AddTicks(7547)
                        },
                        new
                        {
                            Id = 29,
                            Agility = 29,
                            Constitution = 29,
                            CreatedAt = new DateTime(2022, 4, 20, 14, 4, 7, 562, DateTimeKind.Utc).AddTicks(7548),
                            Dexterity = 29,
                            Intelligence = 29,
                            Strength = 29,
                            UpdatedAt = new DateTime(2022, 4, 20, 14, 4, 7, 562, DateTimeKind.Utc).AddTicks(7548)
                        },
                        new
                        {
                            Id = 30,
                            Agility = 30,
                            Constitution = 30,
                            CreatedAt = new DateTime(2022, 4, 20, 14, 4, 7, 562, DateTimeKind.Utc).AddTicks(7549),
                            Dexterity = 30,
                            Intelligence = 30,
                            Strength = 30,
                            UpdatedAt = new DateTime(2022, 4, 20, 14, 4, 7, 562, DateTimeKind.Utc).AddTicks(7549)
                        },
                        new
                        {
                            Id = 31,
                            Agility = 31,
                            Constitution = 31,
                            CreatedAt = new DateTime(2022, 4, 20, 14, 4, 7, 562, DateTimeKind.Utc).AddTicks(7549),
                            Dexterity = 31,
                            Intelligence = 31,
                            Strength = 31,
                            UpdatedAt = new DateTime(2022, 4, 20, 14, 4, 7, 562, DateTimeKind.Utc).AddTicks(7550)
                        },
                        new
                        {
                            Id = 32,
                            Agility = 32,
                            Constitution = 32,
                            CreatedAt = new DateTime(2022, 4, 20, 14, 4, 7, 562, DateTimeKind.Utc).AddTicks(7550),
                            Dexterity = 32,
                            Intelligence = 32,
                            Strength = 32,
                            UpdatedAt = new DateTime(2022, 4, 20, 14, 4, 7, 562, DateTimeKind.Utc).AddTicks(7550)
                        },
                        new
                        {
                            Id = 33,
                            Agility = 33,
                            Constitution = 33,
                            CreatedAt = new DateTime(2022, 4, 20, 14, 4, 7, 562, DateTimeKind.Utc).AddTicks(7551),
                            Dexterity = 33,
                            Intelligence = 33,
                            Strength = 33,
                            UpdatedAt = new DateTime(2022, 4, 20, 14, 4, 7, 562, DateTimeKind.Utc).AddTicks(7551)
                        },
                        new
                        {
                            Id = 34,
                            Agility = 34,
                            Constitution = 34,
                            CreatedAt = new DateTime(2022, 4, 20, 14, 4, 7, 562, DateTimeKind.Utc).AddTicks(7553),
                            Dexterity = 34,
                            Intelligence = 34,
                            Strength = 34,
                            UpdatedAt = new DateTime(2022, 4, 20, 14, 4, 7, 562, DateTimeKind.Utc).AddTicks(7553)
                        },
                        new
                        {
                            Id = 35,
                            Agility = 35,
                            Constitution = 35,
                            CreatedAt = new DateTime(2022, 4, 20, 14, 4, 7, 562, DateTimeKind.Utc).AddTicks(7554),
                            Dexterity = 35,
                            Intelligence = 35,
                            Strength = 35,
                            UpdatedAt = new DateTime(2022, 4, 20, 14, 4, 7, 562, DateTimeKind.Utc).AddTicks(7554)
                        },
                        new
                        {
                            Id = 36,
                            Agility = 36,
                            Constitution = 36,
                            CreatedAt = new DateTime(2022, 4, 20, 14, 4, 7, 562, DateTimeKind.Utc).AddTicks(7555),
                            Dexterity = 36,
                            Intelligence = 36,
                            Strength = 36,
                            UpdatedAt = new DateTime(2022, 4, 20, 14, 4, 7, 562, DateTimeKind.Utc).AddTicks(7555)
                        },
                        new
                        {
                            Id = 37,
                            Agility = 37,
                            Constitution = 37,
                            CreatedAt = new DateTime(2022, 4, 20, 14, 4, 7, 562, DateTimeKind.Utc).AddTicks(7555),
                            Dexterity = 37,
                            Intelligence = 37,
                            Strength = 37,
                            UpdatedAt = new DateTime(2022, 4, 20, 14, 4, 7, 562, DateTimeKind.Utc).AddTicks(7556)
                        },
                        new
                        {
                            Id = 38,
                            Agility = 38,
                            Constitution = 38,
                            CreatedAt = new DateTime(2022, 4, 20, 14, 4, 7, 562, DateTimeKind.Utc).AddTicks(7556),
                            Dexterity = 38,
                            Intelligence = 38,
                            Strength = 38,
                            UpdatedAt = new DateTime(2022, 4, 20, 14, 4, 7, 562, DateTimeKind.Utc).AddTicks(7556)
                        },
                        new
                        {
                            Id = 39,
                            Agility = 39,
                            Constitution = 39,
                            CreatedAt = new DateTime(2022, 4, 20, 14, 4, 7, 562, DateTimeKind.Utc).AddTicks(7557),
                            Dexterity = 39,
                            Intelligence = 39,
                            Strength = 39,
                            UpdatedAt = new DateTime(2022, 4, 20, 14, 4, 7, 562, DateTimeKind.Utc).AddTicks(7557)
                        },
                        new
                        {
                            Id = 40,
                            Agility = 40,
                            Constitution = 40,
                            CreatedAt = new DateTime(2022, 4, 20, 14, 4, 7, 562, DateTimeKind.Utc).AddTicks(7558),
                            Dexterity = 40,
                            Intelligence = 40,
                            Strength = 40,
                            UpdatedAt = new DateTime(2022, 4, 20, 14, 4, 7, 562, DateTimeKind.Utc).AddTicks(7558)
                        },
                        new
                        {
                            Id = 41,
                            Agility = 41,
                            Constitution = 41,
                            CreatedAt = new DateTime(2022, 4, 20, 14, 4, 7, 562, DateTimeKind.Utc).AddTicks(7559),
                            Dexterity = 41,
                            Intelligence = 41,
                            Strength = 41,
                            UpdatedAt = new DateTime(2022, 4, 20, 14, 4, 7, 562, DateTimeKind.Utc).AddTicks(7559)
                        },
                        new
                        {
                            Id = 42,
                            Agility = 42,
                            Constitution = 42,
                            CreatedAt = new DateTime(2022, 4, 20, 14, 4, 7, 562, DateTimeKind.Utc).AddTicks(7559),
                            Dexterity = 42,
                            Intelligence = 42,
                            Strength = 42,
                            UpdatedAt = new DateTime(2022, 4, 20, 14, 4, 7, 562, DateTimeKind.Utc).AddTicks(7560)
                        },
                        new
                        {
                            Id = 43,
                            Agility = 43,
                            Constitution = 43,
                            CreatedAt = new DateTime(2022, 4, 20, 14, 4, 7, 562, DateTimeKind.Utc).AddTicks(7560),
                            Dexterity = 43,
                            Intelligence = 43,
                            Strength = 43,
                            UpdatedAt = new DateTime(2022, 4, 20, 14, 4, 7, 562, DateTimeKind.Utc).AddTicks(7560)
                        },
                        new
                        {
                            Id = 44,
                            Agility = 44,
                            Constitution = 44,
                            CreatedAt = new DateTime(2022, 4, 20, 14, 4, 7, 562, DateTimeKind.Utc).AddTicks(7561),
                            Dexterity = 44,
                            Intelligence = 44,
                            Strength = 44,
                            UpdatedAt = new DateTime(2022, 4, 20, 14, 4, 7, 562, DateTimeKind.Utc).AddTicks(7561)
                        },
                        new
                        {
                            Id = 45,
                            Agility = 45,
                            Constitution = 45,
                            CreatedAt = new DateTime(2022, 4, 20, 14, 4, 7, 562, DateTimeKind.Utc).AddTicks(7562),
                            Dexterity = 45,
                            Intelligence = 45,
                            Strength = 45,
                            UpdatedAt = new DateTime(2022, 4, 20, 14, 4, 7, 562, DateTimeKind.Utc).AddTicks(7562)
                        },
                        new
                        {
                            Id = 46,
                            Agility = 46,
                            Constitution = 46,
                            CreatedAt = new DateTime(2022, 4, 20, 14, 4, 7, 562, DateTimeKind.Utc).AddTicks(7562),
                            Dexterity = 46,
                            Intelligence = 46,
                            Strength = 46,
                            UpdatedAt = new DateTime(2022, 4, 20, 14, 4, 7, 562, DateTimeKind.Utc).AddTicks(7563)
                        },
                        new
                        {
                            Id = 47,
                            Agility = 47,
                            Constitution = 47,
                            CreatedAt = new DateTime(2022, 4, 20, 14, 4, 7, 562, DateTimeKind.Utc).AddTicks(7563),
                            Dexterity = 47,
                            Intelligence = 47,
                            Strength = 47,
                            UpdatedAt = new DateTime(2022, 4, 20, 14, 4, 7, 562, DateTimeKind.Utc).AddTicks(7564)
                        },
                        new
                        {
                            Id = 48,
                            Agility = 48,
                            Constitution = 48,
                            CreatedAt = new DateTime(2022, 4, 20, 14, 4, 7, 562, DateTimeKind.Utc).AddTicks(7564),
                            Dexterity = 48,
                            Intelligence = 48,
                            Strength = 48,
                            UpdatedAt = new DateTime(2022, 4, 20, 14, 4, 7, 562, DateTimeKind.Utc).AddTicks(7564)
                        });
                });

            modelBuilder.Entity("ArenaPlayer", b =>
                {
                    b.HasOne("Gladiator.Core.Entities.Arena", null)
                        .WithMany()
                        .HasForeignKey("OwnedArenasId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Gladiator.Core.Entities.Player", null)
                        .WithMany()
                        .HasForeignKey("OwnersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Gladiator.Core.Entities.BattleLog", b =>
                {
                    b.HasOne("Gladiator.Core.Entities.Gladiator", "Gladiator")
                        .WithMany("Log")
                        .HasForeignKey("GladiatorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Gladiator");
                });

            modelBuilder.Entity("Gladiator.Core.Entities.Gear", b =>
                {
                    b.HasOne("Gladiator.Core.Entities.Gladiator", "Gladiator")
                        .WithMany("Gear")
                        .HasForeignKey("GladiatorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Gladiator.Core.Entities.Stats", "StatModifiersPercent")
                        .WithOne("StatModifiersPercent")
                        .HasForeignKey("Gladiator.Core.Entities.Gear", "StatModifiersPercentId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Gladiator.Core.Entities.Stats", "StatModifiersPoints")
                        .WithOne("StatModifiersPoints")
                        .HasForeignKey("Gladiator.Core.Entities.Gear", "StatModifiersPointsId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Gladiator");

                    b.Navigation("StatModifiersPercent");

                    b.Navigation("StatModifiersPoints");
                });

            modelBuilder.Entity("Gladiator.Core.Entities.Gladiator", b =>
                {
                    b.HasOne("Gladiator.Core.Entities.Player", "Player")
                        .WithMany()
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Gladiator.Core.Entities.School", "School")
                        .WithMany("Gladiators")
                        .HasForeignKey("SchoolId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Gladiator.Core.Entities.Stats", "StatUpdates")
                        .WithOne("StatUpdates")
                        .HasForeignKey("Gladiator.Core.Entities.Gladiator", "StatUpdatesId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Gladiator.Core.Entities.Stats", "Stats")
                        .WithOne("StatGladiator")
                        .HasForeignKey("Gladiator.Core.Entities.Gladiator", "StatsId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Player");

                    b.Navigation("School");

                    b.Navigation("StatUpdates");

                    b.Navigation("Stats");
                });

            modelBuilder.Entity("Gladiator.Core.Entities.School", b =>
                {
                    b.HasOne("Gladiator.Core.Entities.Arena", "Arena")
                        .WithMany("Schools")
                        .HasForeignKey("ArenaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Gladiator.Core.Entities.Player", "Player")
                        .WithMany("Schools")
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Arena");

                    b.Navigation("Player");
                });

            modelBuilder.Entity("Gladiator.Core.Entities.Arena", b =>
                {
                    b.Navigation("Schools");
                });

            modelBuilder.Entity("Gladiator.Core.Entities.Gladiator", b =>
                {
                    b.Navigation("Gear");

                    b.Navigation("Log");
                });

            modelBuilder.Entity("Gladiator.Core.Entities.Player", b =>
                {
                    b.Navigation("Schools");
                });

            modelBuilder.Entity("Gladiator.Core.Entities.School", b =>
                {
                    b.Navigation("Gladiators");
                });

            modelBuilder.Entity("Gladiator.Core.Entities.Stats", b =>
                {
                    b.Navigation("StatGladiator");

                    b.Navigation("StatModifiersPercent");

                    b.Navigation("StatModifiersPoints");

                    b.Navigation("StatUpdates");
                });
#pragma warning restore 612, 618
        }
    }
}
